name: feather_icons_svg
description: Feather Icons SVG allows to customize stroke width in runtime. Uses flutter_svg instead of icon font.
version: 0.2.1
homepage: https://github.com/vaetas/feather_icons_svg

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  path: ^1.9.0

dev_dependencies:
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  recase: ^4.1.0

flutter:
