name: feather_icons_svg
description: Feather Icons SVG allows to customize stroke width in runtime. Uses flutter_svg instead of icon font.
version: 0.2.1
homepage: https://github.com/vaetas/feather_icons_svg

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  path: ^1.8.0

dev_dependencies:
  code_builder: ^4.1.0
  dart_style: ^2.0.3
  recase: ^4.0.0

flutter:
